version: '3'
services:
  database:
    image: postgres:11.13-stretch
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      net_test:
        ipv4_address: 192.162.42.2
    volumes:
      - /home/user/docker:/mnt/
      - /home/user/docker/data:/var/lib/postgresql/data
    healthcheck:
      test:  ["CMD", "pg_isready"]
      timeout: 4s
      retries: 3
    restart: unless-stopped
         
  bacula-server:
    build:
      context: /home/user/docker/bacula11_server/
      dockerfile: bacula11_server
    depends_on:
      database:
        condition: service_healthy   
    ports:
      - "9101:9101"
      - "9102:9102"
      - "9095:9095"
      - "9096:9096"  
    stdin_open: true
    tty: true
    networks:
      net_test:
        ipv4_address: 192.162.42.3
    volumes:
      - /home/user/docker:/mnt/
networks:
  net_test:
    ipam:
      driver: default
      config:
        - subnet: "192.162.42.0/29"
